[workspace]
resolver = "2"
members = ["crates/pavlok-client", "crates/pavlok-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.103"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
pavlok-client = { path = "crates/pavlok-client" }
